Repository Monika-After-Story/MonikaModDev, pull requests merged in 2018-09, with the labels that each got.

#2332 reset freezes in the future
  Monika After Story/game/script-ch30.rpy
Labels: high priority

#2333 Delay idle posing
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/sprite-chart.rpy
Labels: high priority

#2335 Better disable animations
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/zz_hotkeys.rpy
Labels: high priority

#2420 Docking station try to create it
  Monika After Story/game/zz_dockingstation.rpy
Labels: awaiting code review, awaiting testing

#2412 Fix for crashing flow not enabling the UI
  Monika After Story/game/script-story-events.rpy
Labels: awaiting code review, awaiting testing

#2579 changed the link in mas_updater_steam_issue
  Monika After Story/game/updater.rpy
Labels: awaiting changes

#2254 Updates to music and concert topics
  Monika After Story/game/script-topics.rpy
Labels: awaiting code review, awaiting testing

#1869 Added time based dialogue to Tired mood
  Monika After Story/game/script-moods.rpy
Labels: reviewing
