Repository Monika-After-Story/MonikaModDev, pull requests merged in 2018-04, with the labels that each got.

#1344 "Birthday" Mood
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-moods.rpy
Labels: awaiting review

#949 Update Script-Topics
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#915 Love Topic Randomiser
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#898 Monika's Sleep Concerns (Redone)
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1377 Updater Fixes
  Monika After Story/game/screens.rpy
  Monika After Story/game/updater.rpy
Labels: awaiting code review, awaiting testing

#1394 Renpy file/exists fixes
  Monika After Story/game/chess.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updater.rpy
Labels: awaiting code review, awaiting testing

#979 Natsuki's Letter and Professional Help
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1001 Update script-topics.rpy
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1144 Not that far into our relationship changes.
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1080 Yellow Wallpaper
  Monika After Story/game/script-topics.rpy
Labels: awaiting changes, awaiting review

#1025 Asking Monika to explain your relationship to someone
  Monika After Story/game/script-topics.rpy
Labels: awaiting changes

#1421 More expressions for leaning poses and some fixes
  Monika After Story/game/mod_assets/monika/f/face-eyes-smug-n.png
  Monika After Story/game/mod_assets/monika/f/face-eyes-smug.png
  Monika After Story/game/mod_assets/monika/f/face-eyes-wide-n.png
  Monika After Story/game/mod_assets/monika/f/face-eyes-wide.png
  Monika After Story/game/mod_assets/monika/f/face-leaning-def-eyes-left-n.png
  Monika After Story/game/mod_assets/monika/f/face-leaning-def-eyes-normal-n.png
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting changes

#941 Update scriptfarewells
  Monika After Story/game/script-farewells.rpy
Labels: awaiting review

#1457 Hair Down Greeting
  Monika After Story/game/definitions.rpy
  Monika After Story/game/mod_assets/monika/c/def/arms-down-n.png
  Monika After Story/game/mod_assets/monika/c/def/arms-down.png
  Monika After Story/game/mod_assets/monika/c/def/torso-bun-n.png
  Monika After Story/game/mod_assets/monika/c/def/torso-bun.png
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/splash.rpy
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting code review, awaiting testing, high priority

#1460 Hair down bug fix
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/splash.rpy
Labels: high priority

#1461 Fixed template mismatch crash
  Monika After Story/game/event-handler.rpy
Labels: awaiting code review, awaiting testing, high priority

#1467 Event time checker functions
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-topics.rpy
Labels: awaiting changes, high priority

#1468 0.8.0 update scripts
  Monika After Story/game/options.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
Labels: high priority
