Repository Monika-After-Story/MonikaModDev, pull requests merged in 2018-03, with the labels that each got.

#1078 Greetings in French
  Monika After Story/game/script-greetings.rpy
Labels: awaiting review

#804 Smoking Topic
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#999 Mood system
  Monika After Story/game/dev/dev_moods.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-easter-eggs.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-moods.rpy
  Monika After Story/game/script-topics.rpy
Labels: reviewing

#1188 Added the option to apologize
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1223 Nickname Topic
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-ch30.rpy
Labels: awaiting changes

#1219 changed 'our names' topic a little
  Monika After Story/game/script-topics.rpy
Labels: awaiting changes

#628 Watching movies
  Monika After Story/game/movies-info.mms
  Monika After Story/game/zz_hotkey_buttons.rpy
  Monika After Story/game/zz_monikamovie.rpy
Labels: awaiting review

#1286 Missed code rewrite and script-intro changes.
  Monika After Story/game/dev/dev_affection-test.rpy
  Monika After Story/game/script-introduction.rpy
  Monika After Story/game/script-topics.rpy
Labels: awaiting changes

#1312 Increased random seen limit
  Monika After Story/game/script-topics.rpy
Labels: DONT MERGE, discussion

#806 Sea Rewrite
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#819 Fast Food topic
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1292 Dreams topic (rebased)
  Monika After Story/game/script-topics.rpy
Labels: awaiting review
