Repository Monika-After-Story/MonikaModDev, pull requests merged in 2018-08, with the labels that each got.

#1976 Static affection scrambler
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/splash.rpy
Labels: high priority

#2009 Adding a persistent backup system
  Monika After Story/game/definitions.rpy
  Monika After Story/game/dev/dev_tools.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/zz_backup.rpy
Labels: high priority

#1978 New Story
  Monika After Story/game/script-stories.rpy
Labels: awaiting code review, awaiting testing

#2022 Screaming void/monika_death topic update
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#2126 removed skippp true
  Monika After Story/game/script-affection.rpy
Labels: awaiting code review

#2125 increase the loop time to 120 seconds
  Monika After Story/game/zz_transforms.rpy
Labels: awaiting code review

#2128 Added new dialogue for the event, added new hotspots
  Monika After Story/game/script-islands-event.rpy
Labels: awaiting code review, awaiting testing

#2137 Adding affection logging and more
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/zz_pianokeys.rpy
  Monika After Story/game/zz_transforms.rpy
Labels: awaiting code review, awaiting testing

#2105 Added new teary art
  Monika After Story/game/dev/dev_exp_previewer.rpy
  Monika After Story/game/mod_assets/monika/f/face-tears-left-n.png
  Monika After Story/game/mod_assets/monika/f/face-tears-left.png
  Monika After Story/game/mod_assets/monika/f/face-tears-pooled-n.png
  Monika After Story/game/mod_assets/monika/f/face-tears-pooled.png
  Monika After Story/game/mod_assets/monika/f/face-tears-right-n.png
  Monika After Story/game/mod_assets/monika/f/face-tears-right.png
  Monika After Story/game/mod_assets/monika/f/face-tears-up-n.png
  Monika After Story/game/mod_assets/monika/f/face-tears-up.png
  Monika After Story/game/sprite-chart.rpy
Labels: art

#2104 Wink expression arts
  Monika After Story/game/dev/dev_exp_previewer.rpy
  Monika After Story/game/mod_assets/monika/f/face-eyes-winkleft-n.png
  Monika After Story/game/mod_assets/monika/f/face-eyes-winkleft.png
  Monika After Story/game/mod_assets/monika/f/face-eyes-winkright-n.png
  Monika After Story/game/mod_assets/monika/f/face-eyes-winkright.png
  Monika After Story/game/sprite-chart.rpy
Labels: art

#2178 First phase of docking station
  Monika After Story/game/definitions.rpy
  Monika After Story/game/dev/dev_ds_testing.rpy
  Monika After Story/game/mod_assets/monika/mbase
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/splash.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_dockingstation.rpy
Labels: awaiting code review, awaiting testing

#2193 Added "think" eyebrows
  Monika After Story/game/mod_assets/monika/f/face-eyebrows-think-n.png
  Monika After Story/game/mod_assets/monika/f/face-eyebrows-think.png
Labels: art

#2060 added the ability to change gender. …
  Monika After Story/game/script-story-events.rpy
Labels: awaiting code review, awaiting testing

#1410 Feeling scared
  Monika After Story/game/script-moods.rpy
Labels: awaiting review

#2093 Added broken affection path to Sayori Topic
  Monika After Story/game/script-topics.rpy
Labels: awaiting changes
