Repository Monika-After-Story/MonikaModDev, pull requests merged in 2018-05, with the labels that each got.

#1558 Added 2 songs, also music menu adjustments
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/zz_music_selector.rpy
Labels: awaiting code review, awaiting testing

#1530 Added a new flow for greetings, now it has types
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
Labels: awaiting review

#1168 I made a topic about monika_prom
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1581 rigth eyes
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting code review, awaiting testing

#1602 Disable Music 2 topic
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting code review, awaiting testing

#1593 Door greeting close fix
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-greetings.rpy
Labels: awaiting code review, awaiting testing

#1506 Monika tells short stories
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
Labels: awaiting code review

#1623 Adjusted the suntime sliders
  Monika After Story/game/definitions.rpy
  Monika After Story/game/screens.rpy
Labels: awaiting code review, awaiting testing

#1624 Added a Random Chatter Frequency setting
  Monika After Story/game/definitions.rpy
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-ch30.rpy
Labels: awaiting code review, awaiting testing
