Repository Monika-After-Story/MonikaModDev, pull requests merged in 2018-11, with the labels that each got.

#2888 Monika explains how to add custom music
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/zz_history.rpy
  Monika After Story/game/zz_music_selector.rpy
Labels: awaiting testing

#3042 Generic Selection Sidebar
  Monika After Story/game/definitions.rpy
  Monika After Story/game/dev/dev_selector.rpy
  Monika After Story/game/mod_assets/frames/black70_pinkborder100_2px.png
  Monika After Story/game/mod_assets/frames/black70_pinkborder100_5px.png
  Monika After Story/game/mod_assets/frames/selector_overlay.png
  Monika After Story/game/mod_assets/frames/selector_overlay_disabled.png
  Monika After Story/game/mod_assets/frames/selector_top_frame.png
  Monika After Story/game/mod_assets/frames/selector_top_frame_disabled.png
  Monika After Story/game/mod_assets/frames/selector_top_frame_selected.png
  Monika After Story/game/mod_assets/thumbs/clothes-marisa.png
  Monika After Story/game/mod_assets/thumbs/clothes-rin.png
  Monika After Story/game/mod_assets/thumbs/clothes-schooluniform.png
  Monika After Story/game/mod_assets/thumbs/hair-down.png
  Monika After Story/game/mod_assets/thumbs/hair-ponytail.png
  Monika After Story/game/mod_assets/thumbs/locked.png
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/splash.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_extrasmenu.rpy
  Monika After Story/game/zz_selector.rpy
Labels: most lines

#1704 New Power Outage Topic
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1343 Amnesia greeting
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-topics.rpy
Labels: awaiting merge

#3031 Trick
  Monika After Story/game/script-topics.rpy
Labels: DONT MERGE

#3053 Affection based greetings and farewells
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-moods.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_history.rpy
Labels: awaiting testing
