Repository Monika-After-Story/MonikaModDev, pull requests merged in 2018-07, with the labels that each got.

#1843 Expressions edit for topics part 3
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1401 inadequate mood
  Monika After Story/game/script-moods.rpy
Labels: awaiting review

#1341 Monika sings you love songs
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1898 Changed Anniversary Start dates
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-anniversary.rpy
  Monika After Story/game/updates.rpy
Labels: high priority

#1905 Added new expression test generator
  tools/testsgenerator.py
  tools/toolsmenu.py
Labels: awaiting code review

#1929 Fix for bug with calendar overlay clicks
  Monika After Story/game/zz_calendar.rpy
Labels: awaiting testing
