Repository Monika-After-Story/MonikaModDev, pull requests merged in 2018-06, with the labels that each got.

#1727 Fix for greetings
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-greetings.rpy
Labels: awaiting code review, awaiting testing

#1559 Update script-topics.rpy
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1668 Autosaving / Crash detection
  Monika After Story/game/definitions.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/sprite-chart.rpy
Labels: high priority

#1747 Calendar
  Monika After Story/game/definitions.rpy
  Monika After Story/game/dev/dev_calendar.rpy
  Monika After Story/game/dev/dev_greetings.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/event-rules.rpy
  Monika After Story/game/mod_assets/calendar/calendar_bg.png
  Monika After Story/game/mod_assets/calendar/calendar_button_hover.png
  Monika After Story/game/mod_assets/calendar/calendar_button_normal.png
  Monika After Story/game/mod_assets/calendar/calendar_close.png
  Monika After Story/game/mod_assets/calendar/calendar_close_hover.png
  Monika After Story/game/mod_assets/calendar/calendar_day_bg.png
  Monika After Story/game/mod_assets/calendar/calendar_day_disabled_bg.png
  Monika After Story/game/mod_assets/calendar/calendar_day_hover_bg.png
  Monika After Story/game/mod_assets/calendar/calendar_day_name_bg.png
  Monika After Story/game/mod_assets/calendar/calendar_left_arrow.png
  Monika After Story/game/mod_assets/calendar/calendar_left_arrow_hover.png
  Monika After Story/game/mod_assets/calendar/calendar_right_arrow.png
  Monika After Story/game/mod_assets/calendar/calendar_right_arrow_hover.png
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-anniversary.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/splash.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
  Monika After Story/game/zz_calendar.rpy
  Monika After Story/game/zz_hotkey_buttons.rpy
Labels: high priority

#1604 Rework of the Pen Names topic
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1791 Actual fix for non random greetings appearing
  Monika After Story/game/script-greetings.rpy
Labels: awaiting code review, awaiting testing

#1805 Hangman monika Words
  Monika After Story/game/zz_hangman.rpy
Labels: awaiting code review, awaiting testing

#1752 Take Two of the Masturbation Topic Revision
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#1680 add 'happy birthday' to the piano game
  Monika After Story/game/zz_pianokeys.rpy
Labels: awaiting review
