Repository Monika-After-Story/MonikaModDev, pull requests merged in 2019-10, with the labels that each got.

#4804 Blazer arm fix
  Monika After Story/game/mod_assets/monika/c/def/arms-right-restpoint-1-n.png
  Monika After Story/game/mod_assets/monika/c/def/arms-right-restpoint-1.png
Labels: awaiting testing

#4857 Remove Upset Idle sprite
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#4871 Added Holding To Romance Category
  Monika After Story/game/script-topics.rpy
Labels: awaiting testing

#4902 Empty Desk Adjust
  Monika After Story/game/mod_assets/emptydesk-n.png
  Monika After Story/game/mod_assets/emptydesk.png
Labels: awaiting testing

#4904 Gift files in spritepacks
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/bisexualpridethemedribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/blackandwhiteribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/blueandwhitestripedribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/bronzeribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/brownribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/gradientribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/lowpolygradientribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/pinkandwhitestripedribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/rainbowgradientribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/starryblackskyribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/starryredskyribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/transexualpridethemedribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/gifts/whiteonredpolkadotribbon.gift
  spritepacks/released/anonymioo/anonymioo-ribbons/readme.txt
  spritepacks/released/bellmandi86/bellmandi86-spookyhairclips/gifts/bathairclip.gift
  spritepacks/released/bellmandi86/bellmandi86-spookyhairclips/gifts/crescentmoonhairclip.gift
  spritepacks/released/bellmandi86/bellmandi86-spookyhairclips/gifts/ghosthairclip.gift
  spritepacks/released/bellmandi86/bellmandi86-spookyhairclips/gifts/pumpkinhairclip.gift
  spritepacks/released/bellmandi86/bellmandi86-spookyhairclips/readme.txt
  spritepacks/released/finale/Finale-blueshirt/gifts/blueshirt.gift
  spritepacks/released/finale/Finale-blueshirt/readme.txt
  spritepacks/released/jmo/JMO-hairclips/gifts/cherryhairclip.gift
  spritepacks/released/jmo/JMO-hairclips/gifts/hearthairclip.gift
  spritepacks/released/jmo/JMO-hairclips/gifts/musicnotehairclip.gift
  spritepacks/released/jmo/JMO-hairclips/readme.txt
  spritepacks/released/lanvallime/LanvalLime-Ribbons/gifts/coffeeribbon.gift
  spritepacks/released/lanvallime/LanvalLime-Ribbons/gifts/goldribbon.gift
  spritepacks/released/lanvallime/LanvalLime-Ribbons/gifts/hotpinkribbon.gift
  spritepacks/released/lanvallime/LanvalLime-Ribbons/gifts/lilacribbon.gift
  spritepacks/released/lanvallime/LanvalLime-Ribbons/gifts/limegreenribbon.gift
  spritepacks/released/lanvallime/LanvalLime-Ribbons/gifts/navyblueribbon.gift
  spritepacks/released/lanvallime/LanvalLime-Ribbons/gifts/orangeribbon.gift
  spritepacks/released/lanvallime/LanvalLime-Ribbons/gifts/royalpurpleribbon.gift
  spritepacks/released/lanvallime/LanvalLime-Ribbons/gifts/skyblueribbon.gift
  spritepacks/released/lanvallime/LanvalLime-Ribbons/readme.txt
  spritepacks/released/mas/MAS-bunhair/readme.txt
  spritepacks/released/multi/multimokia-blackbow/gifts/blackbow.gift
  spritepacks/released/multi/multimokia-blackbow/readme.txt
  spritepacks/released/orca/Orcaramelo-miku/gifts/hatsunemikucosplay.gift
  spritepacks/released/orca/Orcaramelo-miku/readme.txt
  spritepacks/released/orca/Orcaramelo-shellbikini/gifts/pinkflower.gift
  spritepacks/released/orca/Orcaramelo-shellbikini/gifts/shellbikini.gift
  spritepacks/released/orca/Orcaramelo-shellbikini/readme.txt
  spritepacks/released/velius94/Velius94-PinkShirt/gifts/pinkshirt.gift
  spritepacks/released/velius94/Velius94-PinkShirt/readme.txt
Labels: awaiting testing

#2887 Nobody Makes Sense Song
  Monika After Story/game/script-songs.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#4907 Cleaned logic in monika_breakup
  Monika After Story/game/script-topics.rpy
Labels: awaiting code review, awaiting testing

#4909 allow generic gifts to react multiple times per day
  Monika After Story/game/zz_reactions.rpy
Labels: awaiting testing

#4910 Chokers
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_selector.rpy
  Monika After Story/game/zz_spriteobjects.rpy
  spritepacks/released/trilasent/Trilasent-chokers/gifts/floweredchoker.gift
  spritepacks/released/trilasent/Trilasent-chokers/gifts/simplechoker.gift
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/monika/a/acs-trilasent_choker_flowered-0-0-n.png
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/monika/a/acs-trilasent_choker_flowered-0-0.png
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/monika/a/acs-trilasent_choker_flowered-5-0-n.png
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/monika/a/acs-trilasent_choker_flowered-5-0.png
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/monika/a/acs-trilasent_choker_simple-0-0-n.png
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/monika/a/acs-trilasent_choker_simple-0-0.png
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/monika/a/acs-trilasent_choker_simple-5-0-n.png
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/monika/a/acs-trilasent_choker_simple-5-0.png
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/monika/j/trilasent_acs_choker_flowered.json
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/monika/j/trilasent_acs_choker_simple.json
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/thumbs/acs-trilasent_choker_flowered.png
  spritepacks/released/trilasent/Trilasent-chokers/mod_assets/thumbs/acs-trilasent_choker_simple.png
Labels: awaiting testing

#3266 Add greeting
  Monika After Story/game/script-greetings.rpy
Labels: awaiting review, awaiting testing
