Repository Monika-After-Story/MonikaModDev, pull requests merged in 2019-01, with the labels that each got.

#3377 Added EXtended properties for sprite objects
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting code review, awaiting testing

#3425 Adjust sprite system to work with split arms in leaning
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting testing

#3457 added inactivity detection, triggers after 10 minutes of inactivity
  Monika After Story/game/dev/dev_inactivity_detection.rpy
  Monika After Story/game/event-handler.rpy
Labels: awaiting changes, awaiting code review, awaiting review, awaiting testing

#3462 Change intro scare
  Monika After Story/game/script-introduction.rpy
  Monika After Story/game/script-python.rpy
Labels: awaiting code review, awaiting testing

#1400 Topics Contribution
  Monika After Story/game/script-topics.rpy
Labels: awaiting merge

#3468 Enhanced Apologies
  Monika After Story/game/definitions.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-apologies.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-compliments.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
Labels: DONT MERGE

#3537 backing up topic (reupload)
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting merge

#3565 increase backup size
  Monika After Story/game/zz_backup.rpy
Labels: awaiting merge

#3596 Amendments to ribbon and plushie dialogue topics
  Monika After Story/game/definitions.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_reactions.rpy
Labels: awaiting merge
