Repository Monika-After-Story/MonikaModDev, pull requests merged in 2019-06, with the labels that each got.

#4241 Blinking
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-10.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_weather.rpy
  tools/menutils.py
  tools/sprite.py
  tools/spritemaker.py
  tools/spritepuller.py
  tools/toolsmenu.py
Labels: most lines

#4287 Correct song to play
  Monika After Story/game/script-stories.rpy
Labels: awaiting merge

#4316 santa outfit fix
  Monika After Story/game/mod_assets/monika/c/santa/body-def-n.png
  Monika After Story/game/mod_assets/monika/c/santa/body-def.png
Labels: awaiting testing

#4286 Some cleaning up
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-moods.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-10.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting code review
