Repository Monika-After-Story/MonikaModDev, pull requests merged in 2019-11, with the labels that each got.

#4952 kill bday decor if it doesnt make any sense
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-holidays.rpy
Labels: awaiting code review, awaiting testing

#4945 Moved Scrollable Menu Constants
  Monika After Story/game/dev/dev_unittest.rpy
  Monika After Story/game/script-moods.rpy
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/styles.rpy
  Monika After Story/game/zz_backgrounds.rpy
  Monika After Story/game/zz_weather.rpy
Labels: awaiting testing

#5002 Right RestPoint Arm base update
  Monika After Story/game/mod_assets/monika/b/arms-right-restpoint-1-n.png
  Monika After Story/game/mod_assets/monika/b/arms-right-restpoint-1.png
Labels: awaiting testing

#5017 Added Method
  Monika After Story/game/definitions.rpy
Labels: awaiting code review, awaiting testing

#5024 Greeting Type Timeouts
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
Labels: awaiting merge

#5042 Clean up new day checks
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/zz_reactions.rpy
  Monika After Story/game/zz_weather.rpy
Labels: awaiting code review, awaiting testing
