Repository Monika-After-Story/MonikaModDev, pull requests merged in 2019-02, with the labels that each got.

#3622 Mistle toe event fix
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting merge

#3629 Fixed typo in greeting_long_absence.
  Monika After Story/game/script-greetings.rpy
Labels: awaiting merge

#3649 changed updater server urls to s3
  Monika After Story/game/updater.rpy
Labels: high priority

#3650 Use backup in get aff function
  Monika After Story/game/script-affection.rpy
Labels: high priority

#3227 Add Monika ghost intro and Natsuki desk art
  Monika After Story/game/mod_assets/natsukidesk-n.png
  Monika After Story/game/mod_assets/natsukidesk.png
  Monika After Story/game/mod_assets/other/ghost_monika.png
  Monika After Story/game/script-easter-eggs.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
Labels: awaiting testing

#3680 Typo fixes.
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#2042 Procrastination topic
  Monika After Story/game/script-topics.rpy
Labels: awaiting review

#3035 Mystery Topic
  Monika After Story/game/script-topics.rpy
Labels: awaiting merge

#2101 Bullying topic
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_history.rpy
Labels: awaiting merge

#3799 disabled music button in piano
  Monika After Story/game/zz_pianokeys.rpy
Labels: awaiting merge

#3805 Fix consistence issue with monika_ribbon
  Monika After Story/game/script-topics.rpy
Labels: awaiting merge

#1851 New Game Idle Topic
  Monika After Story/game/script-introduction.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting merge, high priority

#3844 hair no longer locked to def after a restart after switching to a locked hair outfit
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting testing, high priority
