Repository Monika-After-Story/MonikaModDev, pull requests merged in 2019-12, with the labels that each got.

#5083 Make islands event bookmarkable
  Monika After Story/game/script-topics.rpy
Labels: awaiting code review, awaiting testing

#5121 fun facts have labels + new prompt
  Monika After Story/game/script-fun-facts.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting testing

#4578 (Topic) Intrusive Thoughts
  Monika After Story/game/script-topics.rpy
Labels: awaiting review, awaiting testing
