Repository Monika-After-Story/MonikaModDev, pull requests merged in 2019-04, with the labels that each got.

#4017 made first time giving hot choc and coffee use smooth zoom
  Monika After Story/game/zz_reactions.rpy
Labels: awaiting merge

#4018 Hides pf14 event
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting merge

#4019 Added game unlocking on startup
  Monika After Story/game/script-ch30.rpy
Labels: awaiting merge

#4021 Persistent data cleanup
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/zz_backup.rpy
Labels: awaiting merge

#4022 Writing Tip update scripts fixed
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting merge

#4033 Minor fix to monika_rain
  Monika After Story/game/script-topics.rpy
Labels: awaiting merge

#4049 Persistent data loss fix
  Monika After Story/game/event-handler.rpy
Labels: awaiting testing, high priority

#4062 Fix first sesh reset on revisit to main menu
  Monika After Story/game/script.rpy
Labels: awaiting code review

#4073 Made Playsong function better
  Monika After Story/game/script-easter-eggs.rpy
  Monika After Story/game/script-introduction.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/zz_music_selector.rpy
Labels: awaiting merge

#4083 Hehehe -> Ehehe
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-compliments.rpy
Labels: awaiting testing

#4098 Time out fix
  Monika After Story/game/zz_dockingstation.rpy
Labels: awaiting testing

#4107 Updater fixes
  Monika After Story/game/updater.rpy
Labels: awaiting merge

#4109 Long absence flag fix
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting merge

#4110 Affection as another condition
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting merge

#4114 Bday cake fix
  Monika After Story/game/script-holidays.rpy
Labels: awaiting testing

#1946 Adding new dialogue: Stand-Up Comedy
  Monika After Story/game/script-topics.rpy
Labels: awaiting merge
