Repository Monika-After-Story/MonikaModDev, pull requests merged in 2019-09, with the labels that each got.

#4591 Thumb fix
  Monika After Story/game/mod_assets/thumbs/clothes-sundress_white.png
Labels: awaiting testing

#4539 Some more edits
  Monika After Story/game/script-compliments.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-islands-event.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-10.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting merge

#4390 095 typos
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-grammar.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-islands-event.rpy
  Monika After Story/game/script-python.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/zz_dockingstation.rpy
  Monika After Story/game/zz_pianokeys.rpy
Labels: awaiting merge

#4573 Expanded pen name topic + twitter active link
  Monika After Story/game/script-topics.rpy
Labels: awaiting merge

#4624 Fix selector issues
  Monika After Story/game/zz_spriteobjects.rpy
Labels: awaiting code review, awaiting testing
