Repository Monika-After-Story/MonikaModDev, pull requests merged in 2020-01, with the labels that each got.

#5189 Fix pm_var naming
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_history.rpy
  Monika After Story/game/zz_weather.rpy
Labels: awaiting code review, awaiting testing

#5095 Various Fixes
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
  Monika After Story/game/zz_reactions.rpy
  Monika After Story/game/zz_seasons.rpy
  Monika After Story/game/zz_spriteobjects.rpy
Labels: rip

#5201 Player bday update
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
  Monika After Story/game/zz_poems.rpy
Labels: awaiting review, awaiting testing

#5220 Update Fix
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
Labels: bug, rip

#5243 Update outfit thumbs
  Monika After Story/game/mod_assets/thumbs/clothes-new_years_dress.png
  Monika After Story/game/mod_assets/thumbs/clothes-santa_lingerie.png
  Monika After Story/game/mod_assets/thumbs/clothes-sundress_white.png
  spritepacks/released/orca/Orcaramelo-shellbikini/mod_assets/thumbs/clothes-orcaramelo_bikini_shell.png
  spritepacks/released/velius94/Velius94-PinkShirt/mod_assets/thumbs/clothes-velius94_shirt_pink.png
  spritepacks/released/velius94/Velius94-WhiteNavyBlueDress/mod_assets/thumbs/clothes-velius94_dress_whitenavyblue.png
Labels: awaiting testing

#5258 Default ex_props to None
  Monika After Story/game/sprite-chart.rpy
Labels: awaiting testing
