Repository Monika-After-Story/MonikaModDev, pull requests merged in 2020-02, with the labels that each got.

#5279 Adding selector configuration for disabling a selector
  Monika After Story/game/dev/dev_selector.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_selector.rpy
  Monika After Story/game/zz_spritejsons.rpy
Labels: awaiting code review

#5288 Add dump file to main release
  Monika After Story/game/zz_dump.rpy
Labels: awaiting testing

#5275 I love you more fight
  Monika After Story/game/script-topics.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5253 0.10.6 typos
  Monika After Story/game/chess.rpy
  Monika After Story/game/script-compliments.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-introduction.rpy
  Monika After Story/game/script-moods.rpy
  Monika After Story/game/script-python.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
  Monika After Story/game/updater.rpy
  Monika After Story/game/zz_backup.rpy
Labels: DONT MERGE, awaiting review, awaiting testing

#5277 New f14
  Monika After Story/game/definitions.rpy
  Monika After Story/game/mod_assets/monika/a/acs-ear_rose-0-n.png
  Monika After Story/game/mod_assets/monika/a/acs-ear_rose-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ear_rose-5-n.png
  Monika After Story/game/mod_assets/monika/a/acs-ear_rose-5.png
  Monika After Story/game/mod_assets/monika/a/acs-hairties_bracelet_brown-1-1-n.png
  Monika After Story/game/mod_assets/monika/a/acs-hairties_bracelet_brown-1-1.png
  Monika After Story/game/mod_assets/monika/a/acs-hairties_bracelet_brown-2-0-n.png
  Monika After Story/game/mod_assets/monika/a/acs-hairties_bracelet_brown-2-0.png
  Monika After Story/game/mod_assets/monika/a/acs-hairties_bracelet_brown-4-0-n.png
  Monika After Story/game/mod_assets/monika/a/acs-hairties_bracelet_brown-4-0.png
  Monika After Story/game/mod_assets/monika/a/acs-hairties_bracelet_brown-5-1-n.png
  Monika After Story/game/mod_assets/monika/a/acs-hairties_bracelet_brown-5-1.png
  Monika After Story/game/mod_assets/monika/a/acs-heartchoc-0-n.png
  Monika After Story/game/mod_assets/monika/a/acs-heartchoc-0.png
  Monika After Story/game/mod_assets/monika/a/acs-roses-0-n.png
  Monika After Story/game/mod_assets/monika/a/acs-roses-0.png
  Monika After Story/game/mod_assets/monika/c/vday_lingerie/body-def-0-n.png
  Monika After Story/game/mod_assets/monika/c/vday_lingerie/body-def-0.png
  Monika After Story/game/mod_assets/monika/c/vday_lingerie/body-def-1-n.png
  Monika After Story/game/mod_assets/monika/c/vday_lingerie/body-def-1.png
  Monika After Story/game/mod_assets/monika/c/vday_lingerie/body-leaning-def-0-n.png
  Monika After Story/game/mod_assets/monika/c/vday_lingerie/body-leaning-def-0.png
  Monika After Story/game/mod_assets/monika/c/vday_lingerie/body-leaning-def-1-n.png
  Monika After Story/game/mod_assets/monika/c/vday_lingerie/body-leaning-def-1.png
  Monika After Story/game/mod_assets/monika/f/face-eyes-soft-n.png
  Monika After Story/game/mod_assets/monika/f/face-eyes-soft.png
  Monika After Story/game/mod_assets/monika/f/face-leaning-def-eyes-soft-n.png
  Monika After Story/game/mod_assets/monika/f/face-leaning-def-eyes-soft.png
  Monika After Story/game/mod_assets/monika/h/hair-down-front-n.png
  Monika After Story/game/mod_assets/monika/h/hair-down-front.png
  Monika After Story/game/mod_assets/thumbs/clothes-vday_lingerie.png
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-10.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
  Monika After Story/game/zz_dockingstation.rpy
  Monika After Story/game/zz_reactions.rpy
  Monika After Story/game/zz_selector.rpy
  Monika After Story/game/zz_spriteobjects.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5322 Added new song
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-10.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
Labels: awaiting review, awaiting testing

#3372 Topic to Ask Monika: "Do you ever think about our first kiss?"
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-10.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5369 Restart Farewell
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5347 Dynamic Empty Desk
  Monika After Story/game/definitions.rpy
  Monika After Story/game/dev/dev_sprites.rpy
  Monika After Story/game/mod_assets/monika/a/acs-quetzalplushie-0-n.png
  Monika After Story/game/mod_assets/monika/a/acs-quetzalplushie-0.png
  Monika After Story/game/mod_assets/monika/t/chair-def-n.png
  Monika After Story/game/mod_assets/monika/t/chair-def.png
  Monika After Story/game/mod_assets/monika/t/table-def-n.png
  Monika After Story/game/mod_assets/monika/t/table-def-s-n.png
  Monika After Story/game/mod_assets/monika/t/table-def-s.png
  Monika After Story/game/mod_assets/monika/t/table-def.png
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_dockingstation.rpy
  Monika After Story/game/zz_reactions.rpy
  Monika After Story/game/zz_spritejsons.rpy
  Monika After Story/game/zz_spriteobjects.rpy
  Monika After Story/game/zz_weather.rpy
Labels: awaiting merge
