Repository Monika-After-Story/MonikaModDev, pull requests merged in 2020-05, with the labels that each got.

#5692 Fix vars which weren't renamed
  Monika After Story/game/script-topics.rpy
Labels: bug

#5723 Short hair changes
  spritepacks/released/echo/Echo-ShortHairs/mod_assets/monika/h/hair-leaning-def-echo_downshort-front.png
  spritepacks/released/echo/Echo-ShortHairs/mod_assets/monika/h/hair-leaning-def-echo_ponytailshort-front.png
Labels: awaiting testing

#5730 fix an issue in getting sprite object info
  Monika After Story/game/zz_reactions.rpy
Labels: bug

#5722 Added sanity checks for consumable events
  Monika After Story/game/zz_consumables.rpy
Labels: bug

#5773 Add Game topics to the restart blacklist
  Monika After Story/game/zz_games.rpy
Labels: awaiting testing

#5823 Unlock the submods screens w/ any submod installed
  Monika After Story/game/screens.rpy
  Monika After Story/game/zz_submods.rpy
Labels: awaiting testing, bug

#5836 Hemis runs seasonal prog points
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting code review, awaiting testing
