Repository Monika-After-Story/MonikaModDev, pull requests merged in 2020-04, with the labels that each got.

#5541 Various UI code fixes
  .gitignore
  Monika After Story/game/main_menu.rpy
  Monika After Story/game/mod_assets/buttons/generic/hover_bg.png
  Monika After Story/game/mod_assets/buttons/generic/hover_bg_d.png
  Monika After Story/game/mod_assets/buttons/generic/idle_bg.png
  Monika After Story/game/mod_assets/buttons/generic/idle_bg_d.png
  Monika After Story/game/mod_assets/buttons/generic/insensitive_bg.png
  Monika After Story/game/mod_assets/buttons/generic/insensitive_bg_d.png
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-islands-event.rpy
  Monika After Story/game/styles.rpy
  Monika After Story/game/zz_calendar.rpy
  Monika After Story/game/zz_extrasmenu.rpy
  Monika After Story/game/zz_hotkey_buttons.rpy
  Monika After Story/game/zz_music_selector.rpy
  Monika After Story/game/zz_selector.rpy
Labels: awaiting testing

#5535 Fixes PR
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
  Monika After Story/game/zz_hotkeys.rpy
  Monika After Story/game/zz_music_selector.rpy
  Monika After Story/game/zz_shields.rpy
Labels: awaiting review, awaiting testing

#5521 Better Game Handling
  Monika After Story/game/chess.rpy
  Monika After Story/game/definitions.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/pong.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-moods.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/splash.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_games.rpy
  Monika After Story/game/zz_hangman.rpy
Labels: awaiting testing

#5564 Handwritten calendar notes
  Monika After Story/game/mod_assets/calendar/calendar_bg-n.png
  Monika After Story/game/mod_assets/calendar/calendar_bg.png
  Monika After Story/game/mod_assets/calendar/calendar_button_shadow.png
  Monika After Story/game/mod_assets/calendar/calendar_today_bg-n.png
  Monika After Story/game/mod_assets/calendar/calendar_today_bg.png
  Monika After Story/game/mod_assets/calendar/calendar_today_disabled_bg-n.png
  Monika After Story/game/mod_assets/calendar/calendar_today_disabled_bg.png
  Monika After Story/game/mod_assets/calendar/calendar_today_hover_bg.png
  Monika After Story/game/zz_calendar.rpy
Labels: awaiting changes, awaiting testing
