Repository Monika-After-Story/MonikaModDev, pull requests merged in 2020-03, with the labels that each got.

#4971 New story: The Crow and the Pitcher
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-10.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5335 Fix pathing
  Monika After Story/game/script-holidays.rpy
Labels: rip

#5323 Consumables
  Monika After Story/game/definitions.rpy
  Monika After Story/game/mod_assets/monika/a/acs-thermos_mug-0-n.png
  Monika After Story/game/mod_assets/monika/a/acs-thermos_mug-0.png
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_consumables.rpy
  Monika After Story/game/zz_dockingstation.rpy
  Monika After Story/game/zz_dump.rpy
  Monika After Story/game/zz_reactions.rpy
  Monika After Story/game/zz_seasons.rpy
  Monika After Story/game/zz_spriteobjects.rpy
Labels: adds exprops / muxtypes

#5431 Roses as ACS only
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_dockingstation.rpy
  Monika After Story/game/zz_spriteobjects.rpy
Labels: awaiting testing

#3028 New compliment
  Monika After Story/game/script-compliments.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-10.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
Labels: awaiting code review, awaiting testing

#5423 Added 3 Window Reacts
  Monika After Story/game/zz_windowreacts.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#2758 New Topic About Player's Friends
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/zz_history.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5333 Stay with Monika when sick and expanded options
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-moods.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#4801 Talk > Hey, Monika... > Miscellaneous > "I installed Python"
  Monika After Story/game/script-python.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/zz_history.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5455 Fixed Pigtails (But made the pr correctly this time)
  Monika After Story/game/mod_assets/monika/h/hair-leaning-def-orcaramelo_twintails-back-n.png
  Monika After Story/game/mod_assets/monika/h/hair-leaning-def-orcaramelo_twintails-back.png
  Monika After Story/game/mod_assets/monika/h/hair-leaning-def-orcaramelo_twintails-front-n.png
  Monika After Story/game/mod_assets/monika/h/hair-leaning-def-orcaramelo_twintails-front.png
  Monika After Story/game/mod_assets/monika/h/hair-orcaramelo_twintails-back-n.png
  Monika After Story/game/mod_assets/monika/h/hair-orcaramelo_twintails-back.png
  Monika After Story/game/mod_assets/monika/h/hair-orcaramelo_twintails-front-n.png
  Monika After Story/game/mod_assets/monika/h/hair-orcaramelo_twintails-front.png
  spritepacks/released/orca/Orcaramelo-hairs/mod_assets/monika/h/hair-leaning-def-orcaramelo_twintails-back.png
  spritepacks/released/orca/Orcaramelo-hairs/mod_assets/monika/h/hair-orcaramelo_twintails-back.png
  spritepacks/released/orca/Orcaramelo-miku/mod_assets/monika/h/hair-leaning-def-orcaramelo_twintails-back.png
  spritepacks/released/orca/Orcaramelo-miku/mod_assets/monika/h/hair-orcaramelo_twintails-back.png
Labels: awaiting testing
