Repository Monika-After-Story/MonikaModDev, pull requests merged in 2020-12, with the labels that each got.

#6773 Fix MacOS WRS issue (and other things)
  Monika After Story/game/dev/dev_notif_wrs_reload_fix.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/zz_backgrounds.rpy
  Monika After Story/game/zz_windowreacts.rpy
Labels: awaiting code review, awaiting testing, high priority

#6778 Not Exactly Typos
  Monika After Story/game/chess.rpy
  Monika After Story/game/mod_assets/monika/a/acs-quetzalplushie_santahat_mid-0.png
  Monika After Story/game/pong.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-compliments.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-fun-facts.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_consumables.rpy
  Monika After Story/game/zz_reactions.rpy
  Monika After Story/game/zz_spriteobjects.rpy
  Monika After Story/game/zz_windowreacts.rpy
Labels: awaiting code review, awaiting testing

#6820 Switch to GH actions
  .github/workflows/mas_check.yml
  .travis.yml
  README.md
  tools/ghactions.py
Labels: awaiting code review

#6836 Eye color interpolation issues
  Monika After Story/game/script-topics.rpy
Labels: bug
