Repository Monika-After-Story/MonikaModDev, pull requests merged in 2020-06, with the labels that each got.

#5831 Reset consumable if it's prepping but it's not time to have
  Monika After Story/game/zz_consumables.rpy
  Monika After Story/game/zz_reactions.rpy
Labels: awaiting testing

#5777 [New dialogue] Architecture
  Monika After Story/game/script-topics.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5873 Songs are now picked intelligently
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-songs.rpy
Labels: awaiting code review, awaiting testing

#5877 Fixed a crash when generating the shopping list
  Monika After Story/game/zz_consumables.rpy
  Monika After Story/game/zz_extrasmenu.rpy
Labels: bug

#5856 [Topic] Dying the same day
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5852 Update farewells to work similar to greetings
  Monika After Story/game/definitions.rpy
  Monika After Story/game/event-rules.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting testing

#5933 Additional song "Wonderwall" + analysis
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-21.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5906 New song - Can't help falling in love
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-10.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#5952 Falling in Love at a Coffee Shop song
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-10.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
Labels: awaiting code review, awaiting review, awaiting testing
