Repository Monika-After-Story/MonikaModDev, pull requests merged in 2020-07, with the labels that each got.

#5704 0.11.2 Typos
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-brbs.rpy
  Monika After Story/game/script-compliments.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-fun-facts.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-introduction.rpy
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-21.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_consumables.rpy
  Monika After Story/game/zz_reactions.rpy
Labels: awaiting review, awaiting testing

#6019 Code error fix - falling in love at a coffee shop
  Monika After Story/game/script-songs.rpy
Labels: bug

#6052 Add NameError greeting
  Monika After Story/game/script-greetings.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#6057 Better "bad command" for Windows
  Monika After Story/game/script-greetings.rpy
Labels: awaiting testing

#6033 Dict Transitions support (transitions per layer)
  Monika After Story/game/definitions.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/pong.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-anniversary.rpy
  Monika After Story/game/script-brbs.rpy
  Monika After Story/game/script-compliments.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-introduction.rpy
  Monika After Story/game/script-moods.rpy
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/special-effects.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_calendar.rpy
  Monika After Story/game/zz_reactions.rpy
  Monika After Story/game/zz_transforms.rpy
Labels: awaiting testing

#6014 Fix Linux WRS Crash on missing xdotool
  Monika After Story/game/zz_windowreacts.rpy
Labels: awaiting testing

#6022 New song by Avril Lavigne - "When you're gone" V2
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/sprite-chart-00.rpy
  Monika After Story/game/sprite-chart-01.rpy
  Monika After Story/game/sprite-chart-02.rpy
  Monika After Story/game/sprite-chart-10.rpy
  Monika After Story/game/sprite-chart-20.rpy
  Monika After Story/game/sprite-chart-21.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#6117 Some Derands Lose Affection
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updater.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting review, awaiting testing

#6145 Another opendoor greeting - Monika reads documentation, but here's the thing about it...
  Monika After Story/game/script-greetings.rpy
Labels: awaiting code review, awaiting review, awaiting testing

#6027 Safe EV modification functions
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-apologies.rpy
  Monika After Story/game/script-brbs.rpy
  Monika After Story/game/script-compliments.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-fun-facts.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-python.rpy
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/zz_consumables.rpy
  Monika After Story/game/zz_extrasmenu.rpy
  Monika After Story/game/zz_reactions.rpy
  Monika After Story/game/zz_weather.rpy
Labels: awaiting code review, awaiting testing
