Repository Monika-After-Story/MonikaModDev, pull requests merged in 2021-02, with the labels that each got.

#6873 Add window geometry detection/Enhanced Idle, stock
  Monika After Story/game/dev/dev_sprites.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-windowreacts.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/sprite-generator.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_windowreacts.rpy
  Monika After Story/game/zz_windowutils.rpy
Labels: awaiting code review, awaiting testing

#6937 Small Cleanup + Fix
  Monika After Story/game/chess.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_games.rpy
Labels: awaiting testing, bug

#6945 Failsafe EI checks for can_do_windowreacts
  Monika After Story/game/zz_windowutils.rpy
Labels: bug

#6949 A couple EI fixes
  Monika After Story/game/zz_windowutils.rpy
Labels: bug

#6942 Fix F29 Annis
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-anniversary.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting code review, awaiting testing, bug, high priority

#6939 Return home consumables fix
  Monika After Story/game/script-ch30.rpy
Labels: bug

#6999 Chess Update Scripts II
  Monika After Story/game/updates.rpy
Labels: bug

#6998 Better Linux Window Set
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/zz_windowutils.rpy
Labels: awaiting code review, bug

#7003 Fix dismissable text during waits and extends and non-dismissable text after UI setting changes
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/styles.rpy
  Monika After Story/game/zz_hotkeys.rpy
  Monika After Story/game/zz_shields.rpy
Labels: awaiting code review, awaiting testing
