Repository Monika-After-Story/MonikaModDev, pull requests merged in 2021-04, with the labels that each got.

#6901 Bare shoulder exprop correction and allowing for multiple required props
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_spriteobjects.rpy
  spritepacks/released/finale/Finale-Shirt-HappyFace/mod_assets/monika/j/finale_clothes_putonahappyface_shirt.json
  spritepacks/released/finale/Finale-green-dress/mod_assets/monika/j/finale_clothes_green_dress.json
  spritepacks/released/finale/Finale-tanktop/mod_assets/monika/j/finale_clothes_tanktop.json
  spritepacks/released/mocca_bun/Mocca_bun-blackandwhitestripedpullover/mod_assets/monika/j/mocca_bun_blackandwhitestripedpullover.json
  spritepacks/released/orca/Orcaramelo-miku/mod_assets/monika/j/orcaramelo_clothes_hatsune_miku.json
  spritepacks/released/orca/Orcaramelo-shellbikini/mod_assets/monika/j/orcaramelo_clothes_bikini_shell.json
  spritepacks/released/orca/Orcaramelo-shoulderless-sweater/mod_assets/monika/j/orcaramelo_clothes_sweater_shoulderless.json
  spritepacks/released/velius94/Velius94-PinkShirt/mod_assets/monika/j/velius94_clothes_shirt_pink.json
Labels: awaiting merge

#7134 Windows geometry and mouse pos fixes
  Monika After Story/game/zz_windowutils.rpy
Labels: bug

#6460 Strawberry - By Paul Baribeau
  Monika After Story/game/script-songs.rpy
Labels: awaiting code review, awaiting dlg review, awaiting testing

#7168 Fix IO Thread Crash
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/zz_dockingstation.rpy
Labels: bug

#6951 New topic - Zamyatin's 'We'
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting code review, awaiting dlg review, awaiting testing
