Repository Monika-After-Story/MonikaModDev, pull requests merged in 2021-12, with the labels that each got.

#8350 NYE data fix
  Monika After Story/game/updates.rpy
Labels: awaiting testing, awaiting code review

#8154 O31 bug fixes
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-easter-eggs.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/zz_pianokeys.rpy
  Monika After Story/game/zz_selector.rpy
Labels: bug, awaiting testing, awaiting code review

#8217 Typos
  Monika After Story/game/dev/dev_islands.rpy
  Monika After Story/game/mod_assets/games/hangman/1000poemwords.txt
  Monika After Story/game/mod_assets/games/piano/songs/yourreality.json
  Monika After Story/game/mod_assets/monika/h/hair-braided-front.png
  Monika After Story/game/mod_assets/monika/h/hair-def-front.png
  Monika After Story/game/mod_assets/monika/h/hair-down-front.png
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_backgrounds.rpy
Labels: bug, awaiting testing, awaiting code review

#8365 Add exp accessor
  Monika After Story/game/definitions.rpy
Labels: awaiting testing
