Repository Monika-After-Story/MonikaModDev, pull requests merged in 2021-09, with the labels that each got.

#7716 Filterable sprite fixes
  Monika After Story/game/sprite-chart-matrix.rpy
Labels: bug, awaiting code review

#7728 Stop submods from breaking progression flow
  Monika After Story/game/special-effects.rpy
Labels: bug, awaiting testing, awaiting code review, high priority, not a bug

#7714 Block certain hotkeys when the settings menu is opening
  Monika After Story/game/zz_hotkeys.rpy
Labels: awaiting testing, awaiting code review, high priority

#7734 spaceroom filter prog fix
  Monika After Story/game/dev/dev_backgrounds.rpy
  Monika After Story/game/zz_backgrounds.rpy
Labels: awaiting merge

#7145 Add tag replacement to Image Tag Decorations
  Monika After Story/game/dev/deco/fakedeco_1_0_alt.png
  Monika After Story/game/dev/dev_deco.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/zz_backgrounds.rpy
  Monika After Story/game/zz_spritedeco.rpy
Labels: awaiting testing, awaiting code review, requires wiki updates

#7743 Closed eyes tears fix
  Monika After Story/game/dev/dev_sprites.rpy
  Monika After Story/game/mod_assets/sprite_map.json
  Monika After Story/game/sprite-decoder.rpy
Labels: awaiting testing, awaiting code review

#7748 Remove use of depricated funcs + TODOs
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-greetings.rpy
Labels: bug
