Repository Monika-After-Story/MonikaModDev, pull requests merged in 2021-08, with the labels that each got.

#7379 Added a decorator for deprecation
  Monika After Story/game/00utils.rpy
  Monika After Story/game/definitions.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/event-rules.rpy
  Monika After Story/game/import_ddlc.rpy
  Monika After Story/game/options.rpy
  Monika After Story/game/progression.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/sprite-chart-matrix.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
  Monika After Story/game/zz_backgrounds.rpy
  Monika After Story/game/zz_calendar.rpy
  Monika After Story/game/zz_selector.rpy
  Monika After Story/game/zz_weather.rpy
Labels: awaiting code review

#7395 [I hate github lol] Attempt 3 on the Murphy's Law PR. (script-topics.rpy edit)
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting dlg review, awaiting testing, awaiting code review

#7628 [Suggestion] Edits to monika_sophia
  Monika After Story/game/script-topics.rpy
Labels: awaiting dlg review, awaiting testing

#7561 [Pool Topic] - Could it be? Writing Tip #6??
  Monika After Story/game/script-topics.rpy
Labels: awaiting dlg review, awaiting testing, awaiting code review

#7696 Adjust screen props for r7.4
  Monika After Story/game/zz_poemgame.rpy
Labels: awaiting code review
