Repository Monika-After-Story/MonikaModDev, pull requests merged in 2021-07, with the labels that each got.

#6930 Menu option to allow selection of acs_type - adds #5371
  Monika After Story/game/definitions.rpy
  Monika After Story/game/mod_assets/buttons/dropdown/arrow.png
  Monika After Story/game/mod_assets/buttons/dropdown/arrow_d.png
  Monika After Story/game/mod_assets/buttons/dropdown/arrow_hover.png
  Monika After Story/game/mod_assets/buttons/dropdown/arrow_hover_d.png
  Monika After Story/game/zz_selector.rpy
Labels: awaiting code review, awaiting testing

#7338 Removed dashes from hangman
  Monika After Story/game/zz_hangman.rpy
Labels: awaiting merge

#7440 Piano fixes
  Monika After Story/game/zz_pianokeys.rpy
Labels: awaiting code review, awaiting testing, bug

#7235 Adding four new songs.
  Monika After Story/game/script-songs.rpy
Labels: awaiting code review, awaiting dlg review, awaiting testing
