Repository Monika-After-Story/MonikaModDev, pull requests merged in 2021-01, with the labels that each got.

#6634 I deleted our idle sprites
  Monika After Story/game/definitions.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/splash.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_transforms.rpy
  Monika After Story/game/zz_windowreacts.rpy
Labels: awaiting code review, awaiting testing

#6864 Add left/right smug eyes
  Monika After Story/game/dev/dev_exp_previewer.rpy
  Monika After Story/game/mod_assets/monika/f/face-eyes-smugleft.png
  Monika After Story/game/mod_assets/monika/f/face-eyes-smugright.png
  Monika After Story/game/mod_assets/monika/f/face-leaning-def-eyes-smugleft.png
  Monika After Story/game/mod_assets/monika/f/face-leaning-def-eyes-smugright.png
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/sprite-decoder.rpy
Labels: awaiting testing

#6865 Update mas_showEVL to pop from the derand list.
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-topics.rpy
Labels: bug

#6854 Fix singleton
  Monika After Story/game/python-packages/singleton.py
Labels: awaiting code review, awaiting testing

#6909 Adding UTC APIs
  Monika After Story/game/definitions.rpy
  Monika After Story/game/dev/dev_unittest.rpy
  Monika After Story/game/python-packages/pytz/LICENSE.txt
  Monika After Story/game/python-packages/pytz/__init__.py
  Monika After Story/game/python-packages/pytz/exceptions.py
  Monika After Story/game/python-packages/pytz/lazy.py
  Monika After Story/game/python-packages/pytz/tzfile.py
  Monika After Story/game/python-packages/pytz/tzinfo.py
  Monika After Story/game/python-packages/tzlocal/LICENSE.txt
  Monika After Story/game/python-packages/tzlocal/__init__.py
  Monika After Story/game/python-packages/tzlocal/unix.py
  Monika After Story/game/python-packages/tzlocal/utils.py
  Monika After Story/game/python-packages/tzlocal/win32.py
  Monika After Story/game/python-packages/tzlocal/windows_tz.py
  Monika After Story/game/zz_time.rpy
Labels: awaiting code review, awaiting testing

#6932 Small fix for removeDerand
  Monika After Story/game/script-topics.rpy
Labels: bug

#6934 Small fix for mas_bookmarks
  Monika After Story/game/event-handler.rpy
Labels: bug
