Repository Monika-After-Story/MonikaModDev, pull requests merged in 2021-05, with the labels that each got.

#7092 Fix F29 pbday mhs correction
  Monika After Story/game/dev/dev_unittest.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/zz_calendar.rpy
Labels: bug

#7126 Update screen fixes
  Monika After Story/game/screens.rpy
Labels: awaiting code review, awaiting testing

#7216 Hangman
  Monika After Story/game/mod_assets/games/hangman/hm_0.png
  Monika After Story/game/mod_assets/games/hangman/hm_1.png
  Monika After Story/game/mod_assets/games/hangman/hm_2.png
  Monika After Story/game/mod_assets/games/hangman/hm_3.png
  Monika After Story/game/mod_assets/games/hangman/hm_4.png
  Monika After Story/game/mod_assets/games/hangman/hm_5.png
  Monika After Story/game/mod_assets/games/hangman/hm_6.png
  Monika After Story/game/mod_assets/games/hangman/hm_frame.png
  Monika After Story/game/mod_assets/games/hangman/hm_frame_d.png
  Monika After Story/game/mod_assets/games/hangman/hm_s1.png
  Monika After Story/game/mod_assets/games/hangman/hm_s2.png
  Monika After Story/game/mod_assets/games/hangman/hm_sm_0.png
  Monika After Story/game/mod_assets/games/hangman/hm_sm_1.png
  Monika After Story/game/mod_assets/games/hangman/hm_sm_2.png
  Monika After Story/game/mod_assets/games/hangman/hm_sm_3.png
  Monika After Story/game/mod_assets/games/hangman/hm_sm_4.png
  Monika After Story/game/mod_assets/games/hangman/hm_sm_5.png
  Monika After Story/game/mod_assets/games/hangman/hm_sm_6.png
  Monika After Story/game/zz_hangman.rpy
Labels: awaiting testing

#7096 Fix DDLC saves import
  Monika After Story/game/definitions.rpy
  Monika After Story/game/import_ddlc.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-introduction.rpy
  Monika After Story/game/splash.rpy
  Monika After Story/game/updates.rpy
Labels: bug
