Repository Monika-After-Story/MonikaModDev, pull requests merged in 2022-01, with the labels that each got.

#8278 First time crash greet improvements
  Monika After Story/game/definitions.rpy
  Monika After Story/game/mod_assets/sounds/effects/light-switch-sound-effect.mp3
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-story-events.rpy
Labels: awaiting testing, awaiting code review

#8479 0.12.6 Typos
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
  spritepacks/released/briaryoung/briaryoung-sleeveless turtleneck black/mod_assets/thumbs/clothes-briaryoung_sleeveless_turtleneck_black.png
Labels: awaiting code review

#8606 [Story] - "Mind the Gap"
  Monika After Story/game/script-stories.rpy
Labels: awaiting dlg review, awaiting testing, awaiting code review
