Repository Monika-After-Story/MonikaModDev, pull requests merged in 2022-05, with the labels that each got.

#7288 [Chess System Extension] Chess960 Things
  Monika After Story/game/chess.rpy
Labels: awaiting testing, awaiting code review

#8992 Fixed text display when gifting Just Monika thermos
  Monika After Story/game/zz_reactions.rpy
Labels: bug

#8929 Polish hair
  Monika After Story/game/mod_assets/monika/h/hair-leaning-def-wet-front.png
  Monika After Story/game/mod_assets/monika/h/hair-wet-front.png
  Monika After Story/game/zz_spriteobjects.rpy
Labels: art, awaiting testing, high priority

#8996 Cleanup pronouns
  Monika After Story/game/definitions.rpy
  Monika After Story/game/dev/dev_unittest.rpy
  Monika After Story/game/script-ch30.rpy
Labels: awaiting testing, awaiting code review

#8027 Add outfit options to sprite JSON
  Monika After Story/game/definitions.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_spritejsons.rpy
  Monika After Story/game/zz_spriteobjects.rpy
Labels: awaiting merge

#8940 [New Spritepack] Dress (Dark blue, sparkly)
  spritepacks/released/briaryoung/briaryoung-dress dark blue sparkle/gifts/dressdarkbluesparkle.gift
  spritepacks/released/briaryoung/briaryoung-dress dark blue sparkle/mod_assets/monika/c/briaryoung_dress_dark_blue_sparkle/body-def-0.png
  spritepacks/released/briaryoung/briaryoung-dress dark blue sparkle/mod_assets/monika/c/briaryoung_dress_dark_blue_sparkle/body-def-1.png
  spritepacks/released/briaryoung/briaryoung-dress dark blue sparkle/mod_assets/monika/c/briaryoung_dress_dark_blue_sparkle/body-leaning-def-0.png
  spritepacks/released/briaryoung/briaryoung-dress dark blue sparkle/mod_assets/monika/c/briaryoung_dress_dark_blue_sparkle/body-leaning-def-1.png
  spritepacks/released/briaryoung/briaryoung-dress dark blue sparkle/mod_assets/monika/j/briaryoung_clothes_dress_dark_blue_sparkle.json
  spritepacks/released/briaryoung/briaryoung-dress dark blue sparkle/mod_assets/thumbs/clothes-briaryoung_dress_dark_blue_sparkle.png
  spritepacks/released/briaryoung/briaryoung-vcut crossed straps tanktop white/gifts/vcutcrossedstrapstanktopwhite.gift
  spritepacks/released/briaryoung/briaryoung-vcut crossed straps tanktop white/mod_assets/monika/c/briaryoung_vcut_crossed_straps_tanktop_white/body-def-0.png
  spritepacks/released/briaryoung/briaryoung-vcut crossed straps tanktop white/mod_assets/monika/c/briaryoung_vcut_crossed_straps_tanktop_white/body-def-1.png
  spritepacks/released/briaryoung/briaryoung-vcut crossed straps tanktop white/mod_assets/monika/c/briaryoung_vcut_crossed_straps_tanktop_white/body-leaning-def-0.png
  spritepacks/released/briaryoung/briaryoung-vcut crossed straps tanktop white/mod_assets/monika/c/briaryoung_vcut_crossed_straps_tanktop_white/body-leaning-def-1.png
  spritepacks/released/briaryoung/briaryoung-vcut crossed straps tanktop white/mod_assets/monika/j/briaryoung_clothes_vcut_crossed_straps_tanktop_white.json
  spritepacks/released/briaryoung/briaryoung-vcut crossed straps tanktop white/mod_assets/thumbs/clothes-briaryoung_vcut_crossed_straps_tanktop_white.png
Labels: art, awaiting dlg review, awaiting testing, awaiting code review

#9172 [New Outfit] Button Up (Flowered)
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/gifts/buttonupflowered.gift
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/arms-crossed-5.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/arms-leaning-def-left-def-10.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/arms-leaning-def-right-def-5.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/arms-left-down-0.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/arms-left-rest-10.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/arms-right-down-0.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/arms-right-point-0.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/arms-right-restpoint-10.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/arms-steepling-10.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/body-def-0.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/body-def-1.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/body-leaning-def-0.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/c/briaryoung_button_up_flowered/body-leaning-def-1.png
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/monika/j/briaryoung_clothes_button_up_flowered.json
Labels: art, awaiting dlg review, awaiting testing, awaiting code review

#9187 Small thumb fix
  spritepacks/released/briaryoung/briaryoung-button-up-flowered/mod_assets/thumbs/clothes-briaryoung_button_up_flowered.png
  spritepacks/released/briaryoung/briaryoung-dress dark blue sparkle/mod_assets/thumbs/clothes-briaryoung_dress_dark_blue_sparkle.png
Labels: art

#9186 [Spritepack] - Pink Kimono
  spritepacks/released/mayjay/mayjay_pink_kimono/gifts/pinkkimono.gift
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-crossed-10.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-crossed-5.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-leaning-def-left-def-10.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-leaning-def-right-def-10.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-leaning-def-right-def-5.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-left-down-0.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-left-rest-10.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-right-down-0.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-right-point-0.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-right-restpoint-10.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/arms-steepling-10.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/body-def-0.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/body-def-1.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/body-leaning-def-0.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/c/mayjay_pink_kimono/body-leaning-def-1.png
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/monika/j/mayjay_clothes_pink_kimono.json
  spritepacks/released/mayjay/mayjay_pink_kimono/mod_assets/thumbs/clothes-mayjay_pink_kimono.png
Labels: art, awaiting dlg review, awaiting testing, awaiting code review
