Repository Monika-After-Story/MonikaModDev, pull requests merged in 2022-09, with the labels that each got.

#9232 Fix `extend` jarring
  Monika After Story/game/screens.rpy
Labels: bug, awaiting testing

#9379 Some more NOU improvements
  Monika After Story/game/script-moods.rpy
  Monika After Story/game/zz_cardgames.rpy
  Monika After Story/game/zz_games.rpy
Labels: awaiting testing, awaiting code review

#9265 Remove deprecated funcs
  Monika After Story/game/definitions.rpy
  Monika After Story/game/dev/dev_sprites.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-compliments.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-fun-facts.rpy
  Monika After Story/game/script-grammar.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-islands-event.rpy
  Monika After Story/game/script-moods.rpy
  Monika After Story/game/script-python.rpy
  Monika After Story/game/script-songs.rpy
  Monika After Story/game/script-stories.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/script-windowreacts.rpy
  Monika After Story/game/zz_calendar.rpy
  Monika After Story/game/zz_cardgames.rpy
  Monika After Story/game/zz_consumables.rpy
  Monika After Story/game/zz_games.rpy
  Monika After Story/game/zz_monikamovie.rpy
  Monika After Story/game/zz_reactions.rpy
  Monika After Story/game/zz_weather.rpy
  Monika After Story/game/zz_windowutils.rpy
Labels: awaiting testing, awaiting code review

#8399 Add API Key settings screen + framework
  .gitignore
  Monika After Story/game/0imports.rpy
  Monika After Story/game/0utils.rpy
  Monika After Story/game/definitions.rpy
  Monika After Story/game/dev/dev_apikeys.rpy
  Monika After Story/game/options.rpy
  Monika After Story/game/python-packages/certifi/__init__.py
  Monika After Story/game/python-packages/certifi/core.py
  Monika After Story/game/python-packages/ssl/__init__.py
  Monika After Story/game/python-packages/ssl/linux/32/_ssl.so
  Monika After Story/game/python-packages/ssl/linux/32/linux32_ssl.pyo
  Monika After Story/game/python-packages/ssl/linux/64/_ssl.so
  Monika After Story/game/python-packages/ssl/linux/64/linux64_ssl.pyo
  Monika After Story/game/python-packages/ssl/mac/64/_ssl.so
  Monika After Story/game/python-packages/ssl/mac/64/mac64_ssl.pyo
  Monika After Story/game/python-packages/ssl/windows/32/_ssl.pyd
  Monika After Story/game/python-packages/ssl/windows/32/win32_ssl.pyo
  Monika After Story/game/screens.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-python.rpy
  Monika After Story/game/styles.rpy
  Monika After Story/game/zz_apikeys.rpy
  Monika After Story/game/zz_spritejsons.rpy
  Monika After Story/game/zz_threading.rpy
Labels: awaiting testing, awaiting code review

#8745 organized reset code
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/script-moods.rpy
  Monika After Story/game/zz_dockingstation.rpy
  Monika After Story/game/zz_games.rpy
Labels: awaiting testing, awaiting code review, high priority

#9539 Update README.md
  Monika After Story/README.html
  README.md
Labels: high priority
