Repository Monika-After-Story/MonikaModDev, pull requests merged in 2022-12, with the labels that each got.

#9787 Fix 922 nts bug
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
Labels: bug, awaiting testing, awaiting code review, high priority

#9701 Better hangman unlock dlg paths
  Monika After Story/game/script-story-events.rpy
Labels: awaiting dlg review, awaiting testing, awaiting code review

#9582 Replace special Windows characters in path name (fix #9557)
  Monika After Story/game/definitions.rpy
  Monika After Story/game/script-holidays.rpy
Labels: awaiting testing, awaiting code review
