Repository Monika-After-Story/MonikaModDev, pull requests merged in 2022-10, with the labels that each got.

#9583 Ahoge filter fix
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_bent-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_bent-5.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_curl-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_curl-5.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_double-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_double-5.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_heart-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_heart-5.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_lightning-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_lightning-5.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_sharp-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_sharp-5.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_simple-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_simple-5.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_small-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_small-5.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_swoop-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_swoop-5.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_twisty-0.png
  Monika After Story/game/mod_assets/monika/a/acs-ahoge_twisty-5.png
Labels: art

#9649 Fix reference to ERR_ON_CHG_MSG (resolve #9648)
  Monika After Story/game/zz_apikeys.rpy
Labels: bug, awaiting testing

#9618 Update shower greeting outfit selection
  Monika After Story/game/script-greetings.rpy
Labels: awaiting testing

#9598 2B spack
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_spriteobjects.rpy
  spritepacks/released/hatana/hatana-2B/gifts/2bcosplay.gift
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-crossed-10.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-crossed-5.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-leaning-def-left-def-10.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-leaning-def-right-def-10.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-leaning-def-right-def-5.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-left-down-0.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-left-rest-10.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-right-down-0.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-right-point-0.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-right-restpoint-10.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/arms-steepling-10.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/body-def-0.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/body-def-1.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/body-leaning-def-0.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/c/hatana_2b/body-leaning-def-1.png
  spritepacks/released/hatana/hatana-2B/mod_assets/monika/j/hatana_clothes_yorha_2b_cosplay.json
  spritepacks/released/hatana/hatana-2B/mod_assets/thumbs/clothes-hatana_2b.png
Labels: awaiting dlg review, awaiting testing, awaiting code review

#9628 Backup awareness
  Monika After Story/game/0config.rpy
  Monika After Story/game/options.rpy
  Monika After Story/game/script-affection.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-story-events.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_backup.rpy
Labels: awaiting dlg review, awaiting testing, awaiting code review
