Repository Monika-After-Story/MonikaModDev, pull requests merged in 2022-02, with the labels that each got.

#8656 Bad name false positive fix
  Monika After Story/game/script-story-events.rpy
Labels: awaiting testing, awaiting code review

#8594 0.12.7 Typos
  Monika After Story/game/script-fun-facts.rpy
  Monika After Story/game/script-topics.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/updates_topics.rpy
  Monika After Story/game/zz_spriteobjects.rpy
Labels: awaiting dlg review, awaiting testing, awaiting code review

#7576 New idle mode exps + fixes
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-brbs.rpy
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/updates.rpy
Labels: awaiting testing, awaiting code review, high priority

#8542 d25/nye fixes
  Monika After Story/game/script-holidays.rpy
  Monika After Story/game/updates.rpy
  Monika After Story/game/zz_history.rpy
Labels: bug

#8619 Add Event List wrappers and Event Context
  Monika After Story/game/0utils.rpy
  Monika After Story/game/dev/dev_misc.rpy
  Monika After Story/game/dev/dev_unittest.rpy
  Monika After Story/game/event-handler.rpy
  Monika After Story/game/script-ch30.rpy
Labels: awaiting testing, awaiting code review, high priority

#6915 New greeting, new clothes and hair, and hair sprite adjustments
  Monika After Story/game/event-rules.rpy
  Monika After Story/game/mod_assets/monika/a/acs-water_drops-0.png
  Monika After Story/game/mod_assets/monika/a/acs-water_drops-5.png
  Monika After Story/game/mod_assets/monika/c/bath_towel_white/body-def-0.png
  Monika After Story/game/mod_assets/monika/c/bath_towel_white/body-def-1.png
  Monika After Story/game/mod_assets/monika/c/bath_towel_white/body-leaning-def-0.png
  Monika After Story/game/mod_assets/monika/c/bath_towel_white/body-leaning-def-1.png
  Monika After Story/game/mod_assets/monika/h/hair-leaning-def-wet-back.png
  Monika After Story/game/mod_assets/monika/h/hair-leaning-def-wet-front.png
  Monika After Story/game/mod_assets/monika/h/hair-wet-back.png
  Monika After Story/game/mod_assets/monika/h/hair-wet-front.png
  Monika After Story/game/script-ch30.rpy
  Monika After Story/game/script-farewells.rpy
  Monika After Story/game/script-greetings.rpy
  Monika After Story/game/sprite-chart.rpy
  Monika After Story/game/zz_spriteobjects.rpy
Labels: awaiting dlg review, awaiting testing, awaiting code review, high priority

#8902 Fix undefined var
  Monika After Story/game/event-handler.rpy
Labels: bug, awaiting testing, awaiting code review
