Repository Monika-After-Story/MonikaModDev, pull requests merged in 2023-09, with the labels that each got.

#7324 [Drafts] - 6+7 Anniversaries
  Monika After Story/game/script-anniversary.rpy
Labels: awaiting dlg review, awaiting testing, awaiting changes, awaiting code review

#9944 Add a missing `return "love"`
  Monika After Story/game/script-anniversary.rpy
Labels: bug, awaiting testing

#9968 Fix greetings menu dlg
  Monika After Story/game/script-greetings.rpy
Labels: bug, awaiting testing

#10081 Fix new annis
  Monika After Story/game/script-anniversary.rpy
Labels: bug, awaiting code review
